name: SmileyCoin CI build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu_no_gui:

    runs-on: ubuntu-20.04

    steps:
    - name: dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libdb5.3++-dev libboost-all-dev libssl-dev libtool autoconf pkg-config
    - uses: actions/checkout@v2
    - name: configure
      run: ./autogen.sh && ./configure --with-gui=no
    - name: make
      run: make
    - name: make check
      run: make check
